### ISSUE TITLE
Suggestions for install manual

### ISSUE THREAD

**Issue by erenes** [yourlocalbox/lox-standard#1]
Hi guys, 

I'm currently trying to install lox-standard on an Ubuntu server 15.04 installation, and running into some trouble (that I have hopefully solved by the time I finish this post): 

1. The apt-get line contains packages that do not exist (anymore?), I changed it to be: 
`sudo apt-get install apache2 libapache2-mod-php5 mariadb-server git php5-mysql php5-intl php5-cli`

2. Running Composer also tries to connect to the database, but my database was not setup yet. Perhaps move the database configuration up? 

3. After hardening the database, I could not log in to the root account unless using sudo. <b>Which is by design, of course,</b> but might warrant a warning to create the localbox user and database <i>before</i> hardening the installation? (If my slightly more linux-fearful colleagues would have followed the guide, they would not have been able to resolve this issue)

4. The note: `if you don't have a valid parameters.yml the script will ask you for the settings.` is fine. And although the prompts speak for themselves. It's strange that we are first asked to run `composer update` and later find out there was an optional step <i>before</i> that. 

5. The documentation says that the post-install script will configure apache for me, but from the script I don't see any apache configuration being written. It would also be nice to know which directory to map in apache, and possible rewrites to configure. 

6. Additional notes for Debian/Ubuntu: 
  * default apache username is `www-data`
  * if you want to create a deb package, apache site configuration is included in `/etc/apache2/sites-available`, and when enabled a symlink is put in `/etc/apache2/sites-enabled` (using a2ensite)
  * Enable rewrite mod by: `$ (sudo) a2enmod rewrite`

Right now I have the basic website up and running, but am missing the rewrites. And I have the impression that I don't currently have a completely working installation of localbox (but I'm sure the developer who requested the installation will tell me soon enough ;-))

I realize you are still in development, but I thought it might be good to get some feedback from the outside world :)

**Comment by imtal** [comment]
Hello Erik, 

The Localbox backend undergoes a major rewrite at this moment. Reason is that they want to get rid of the Symfony framework that brings a lot of dependencies and update problems. The new server software is much simpler and easier to install, I am told. I do not know when the software becomes available in the public repositories but I expect before the end of the year.

**Comment by erenes** [comment]
Thanks for the response, I'm looking forward to the new version :)
